### ISSUE TITLE
links URL explanation

### ISSUE THREAD

**Issue by de-Generation** [charlesZoul/debrid.sh#1]
Hi,
Could you give some example on how should we define links in **list.txt** file?
I tried my media folder link and downloading link in browser. but I ended up with file not found error:

`[ERREUR] Lien <my-slot-link> non géré
./debrid.sh: line 38: tmp.url: No such file or directory`

**Comment by charlesZoul** [comment]
The file contain all the links I want to debrid, 1 by line
